version: '3'
services:
    jekyll:
        image: jekyll/jekyll:4.0
        environment:
            - JEKYLL_ENV=production bundle exec jekyll build

        # No incremental change - update gem and run local
        #command: >
        #    /bin/bash -c "bundle update
        #    && bundle install
        #    && bundle exec jekyll serve --host 0.0.0.0 --config _config.yml --watch "

        # No incremental change - don't update gem and run local
        command: "jekyll serve"

        volumes:
            - .:/srv/jekyll

        ports:
            - 4000:4000
